# -*- coding: utf-8 -*-
"""MB CBSOT SIP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jNel509c1q2sXLErHYppgfRRrgf8wZK

### 23 June
"""

!pip install datasets

from datasets import load_dataset

dataset = load_dataset("CShorten/ML-ArXiv-Papers", split = 'train')

print(dataset)

dataset[0]

import pandas as pd

df = pd.DataFrame(dataset)
df

df.columns

df = df[['title', 'abstract']] # Data Cleaning # Irrelevant columns removed from the dataset.

df

df.shape

df = df.head(15000)

df.shape

df.isnull().sum()

df["paper_text"] = df["title"] + " " + df["abstract"]

df[["paper_text"]].head()

type(df[["paper_text"]])

df[["paper_text"]].head()

print(df["paper_text"].iloc[0])

df = df.head(15000)

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print(type(model))

df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex = False) # for distinction b/w 2 '\n' newline and regex. \n also replaced by space
df["paper_text"] = df["paper_text"].str.strip() # to remove starting and ending spaces

sample_text = df["paper_text"].iloc[0]

sample_text

embedding = model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

embedding[:56]

sample_embedding = model.encode(df["paper_text"].head(5).to_list())

print(sample_embedding)

print(sample_embedding.shape)

"""### 24 June"""

from sklearn.metrics.pairwise import cosine_similarity

# similarity = cosine_similarity(sample_embedding[0], sample_embedding[0])
# print(similarity)

similarity = cosine_similarity(sample_embedding[0].reshape(1, -1), sample_embedding[0].reshape(1, -1))
print(similarity)

similarity = cosine_similarity(sample_embedding[0].reshape(1, -1), sample_embedding[1].reshape(1, -1)) # keep rows = 1, no of cols = adjustable (x)
print(similarity)

for i in range(1,5):
  sim = similarity = cosine_similarity(sample_embedding[0].reshape(1, -1), sample_embedding[i].reshape(1, -1))
  print(sim)

"""# Generate Full Embedding"""

import os
import numpy as np

drive_path = "/content/drive/MyDrive/cbsot ml/paper_embeddings.npy"
local_path = "paper_embeddings.npy"

if os.path.exists(drive_path):
    print("Loading saved embeddings from Google Drive")
    embeddings = np.load(drive_path)

elif os.path.exists(local_path):
    print("Loading uploaded embeddings file")
    embeddings = np.load(local_path)

else:
    print("Generating embeddings")
    embeddings = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )

# embedding = model.encode(df["paper_text"].to_list(), batch_size = 32, show_progress_bar = True)

print(embedding.shape)
print(type(embedding))

embedding.dtype

!pip install faiss-cpu

import faiss

# faiss.normalize_L2(embedding)

# index = faiss.IndexFlatIP(384)

# index.add(embedding)

drive_path = "/content/drive/MyDrive/cbsot ml/paper_faiss.index"
local_path = "paper_faiss.index"

if os.path.exists(drive_path):

    print("Loading existing FAISS index from Google Drive")
    index = faiss.read_index(drive_path)

elif os.path.exists(local_path):

    print("Loading uploaded FAISS index")
    index = faiss.read_index(local_path)

else:

    print("Creating new FAISS index")

    faiss.normalize_L2(embeddings)

    index = faiss.IndexFlatIP(384)
    index.add(embeddings)

    # Save locally
    faiss.write_index(index, local_path)

    print("FAISS index saved successfully!")

print(index.ntotal)

query = "deep learning for medical image analysis"
query_embedding = model.encode(query)
query_embedding = query_embedding.reshape(1, -1)
query_embedding.shape

# query = "deep learning for medical image analysis"
# query_embedding = model.encode(query)
# query_embedding = query_embedding.reshape(1, -1)
# query_embedding

faiss.normalize_L2(query_embedding)

D, I = index.search(query_embedding, 5)

print(D)  # Similarity Score

print(I) # Index of the similarity score

"""## 26 June"""

print(df.iloc[10466]["title"])

print(df.iloc[10466]["abstract"])

print(df.iloc[11873]["title"]) # semantic meaning

def search_paper(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)
    return D, I

D, I = search_paper("deep learning for medical image analysis")
print(D)
print(I)

def search_paper(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)
    for score, idx in zip(D[0], I[0]):
      print("Similarity Score", score)
      print("Title", df.iloc[idx]["title"])
      print("Abstract", df.iloc[idx]["abstract"][:500])
      print()
      # title = df.iloc[idx]["title"]
      # print(f"Title: {title}")
      # abstract = df.iloc[idx]["abstract"]
      # print(f"Abstract: {abstract}")

search_paper("deep learning for medical image analysis")

!pip install transformers==4.46.3

from transformers import pipeline
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn",
)

type(summarizer)

summary = summarizer(df.iloc[10466]["abstract"], max_length=120, min_length=40)
print(summary)

type(summary)

type(summary[0])

summary[0]["summary_text"]

for score, idx in zip(D[0], I[0]):
      print("Similarity Score", score)
      print("Title", df.iloc[idx]["title"])
      print("Abstract", df.iloc[idx]["abstract"][:500])
      print()

      summary = summarizer(df.iloc[idx]["abstract"], max_length=120, min_length=40)
      print(summary[0]["summary_text"])
      print()

"""# 30 June"""

def search_and_summarize(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):
        print("Similarity score", score)
        print("Title", df.iloc[idx]["title"])
        print("Abstract", df.iloc[idx]["abstract"][:500])
        print()

        summary = summarizer(
            df.iloc[idx]["abstract"],
            max_length=120,
            min_length=40,
            do_sample=False
        )

        print(summary)
        print(summary[0]["summary_text"])
        print()

search_and_summarize("Deep learning in medical imaging", k = 5)

!pip install keybert==0.8.5

from keybert import KeyBERT

kw_model = KeyBERT(model)

type(kw_model) # model = SentenceTransformer("all-MiniLM-L6-v2")

print(df.iloc[10466]["abstract"])

text = df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)

print(keywords)

print(type(keywords))

print(type(keywords[0]))

keywords = kw_model.extract_keywords(text,keyphrase_ngram_range=(1, 3),stop_words="english")

print(keywords)

"""Extra remarks (for me):

Project: AI Research Paper Intelligence System



will have to add NER in the original project

u will get the project flow idea from the ipynb and py file, read that carefully

keyBERT, ngrams, stop word removal



workflow of the project implemented:

user query -> sentence transformer -> query embedding -> faiss semantic search -> top k similar paper -> BART summarization -> result

KeyBERT (important keyword extraction) - algorithm used

deep learning, nlp project

extracting candidate pharases, ngrams



what to do more on this (add in this project - besides source code)

(ideas - sir gave, can use 1 or more)

1. Python Medical Dataset with FASTAPI - tell its entinties, so this mdoel must thell that fastapi - framework and python is a programming language distinction.

2. Name Entity Recognition (NER)

eg --> pytorch (framework), google (organization), BERT (model) -- so these are entities, NER Trained on a generic dataset
"""